### ISSUE TITLE
Where to write which pcf file should plugin use?

### ISSUE THREAD

**Issue by beastedout** [Totenfluch/StoreParticleExtension#1]
in spawn effect/hit effect/kill effect/auras/particles, where to mention which pcf file to use?

Good Plugin btw!

**Comment by Totenfluch** [comment]
use the plugin thread for questions,

you don't need to. just have them precached on the server

**Comment by beastedout** [comment]
Oh, my bad.
Thanks for the answer! 😉 \(^-^)/
